name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: v16.13.0
      - run: corepack enable
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
      - run: yarn test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: v16.13.0
      - run: corepack enable
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
      - run: npx playwright install --with-deps
      - run: yarn test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  hygiene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: v16.13.0
      - run: corepack enable
      - run: yarn install --immutable --immutable-cache
      - run: yarn lint
      - run: yarn fmt
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v3
        with:
          node-version: v16.13.0
          registry-url: https://registry.npmjs.org/
      - run: corepack enable
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
      - run: echo "PKG_VERSION=$(node ./scripts/get-version.js ${{ github.event.pull_request.head.ref }})" >> $GITHUB_ENV
      - run: echo "TAG_NAME=$(node ./scripts/get-tag.js ${{ github.event.pull_request.head.ref }})" >> $GITHUB_ENV
      - run: PKG_VERSION=$PKG_VERSION yarn version:pre
      - run: |
          echo npmAuthToken: "$NODE_AUTH_TOKEN" >> ./.yarnrc.yml
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: TAG_NAME=$TAG_NAME yarn publish:pre
