name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: v16.13.0
      - run: corepack enable
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
      - run: yarn test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: v16.13.0
      - run: corepack enable
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
      - run: npx playwright install --with-deps
      - run: yarn test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  hygiene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: v16.13.0
      - run: corepack enable
      - run: yarn install --immutable --immutable-cache
      - run: yarn lint
      - run: yarn fmt
  npm:
    runs-on: ubuntu-latest
#    needs: [test, e2e, hygiene]
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: v16.13.0
      - run: corepack enable
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
      - run: echo $(node ./scripts/get-version.js)
#      - run: PKG_VERSION=${{ LATEST_NPM_VERSION }}-${{ github.run_id }} yarn version:beta
#      - run: yarn publish
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
